
KERNEL_MODULE_NAME := kernel_memory_map_test

# '$(KERNEL_MODULE_NAME).ko' module:
obj-m += $(KERNEL_MODULE_NAME).o

# '$(KERNEL_MODULE_NAME).o' sources:
$(KERNEL_MODULE_NAME)-y += module.o
$(KERNEL_MODULE_NAME)-y += print_kernel_memory_map.o

# Note: '$(src)' is defined by kernel build system as absolute path
# pointing to directory with this Kbuild file
ccflags-y += -I$(src)

# Tag to filter debug print
#ccflags-y += -DPRINTK_TAG=\"KernelMemoryMap\"
ccflags-y += -DPRINTK_TAG=\"KMM\"

# uncomment/comment to enable/disable debug print
#ccflags-y += -D__DEBUG__
